# -*- coding: utf-8 -*-
"""Drug Property Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hze2NgVuYi6-nE9DDQlcxvtB1Z-BU4wD
"""

!pip install rdkit

from rdkit import Chem
from rdkit.Chem import Descriptors
import pandas as pd

data = pd.DataFrame({

    "Molecules Name":["Aspirin", "Paracetamol", "Ibuprofen", "Caffeine", "Metformin"],

    "Smiles":["CC(=O)OC1=CC=CC=C1C(=O)O",    # Aspirin
        "CC(=O)NC1=CC=C(O)C=C1",              # Paracetamol
        "CC(C)CC1=CC=C(C=C1)C(C)C(=O)O",      # Ibuprofen
        "Cn1cnc2c1c(=O)n(C)c(=O)n2C",         # Caffeine
        "CNC(N)=NCCC(=O)N"]                    # Metformin]
})

data

"""**Molecule Smiles convert to Mols**"""

data["Mols"] = data["Smiles"].apply(Chem.MolFromSmiles)
data

"""**Properties Calculation for Molecule**

* Molecular Weight

* LogP

* Hydrogen bond donors

* Hydrogen bond acceptors

* Surface area (TPSA)

* Number of rings

* Number of rotatable bonds


"""

# Function to calculate properties of a molecule

def calc_properties(Mols):

    mw = Descriptors.MolWt(Mols)
    logp = Descriptors.MolLogP(Mols)
    hbd = Descriptors.NumHDonors(Mols)
    hba = Descriptors.NumHAcceptors(Mols)
    tpsa = Descriptors.TPSA(Mols)
    rings = Descriptors.RingCount(Mols)
    rot = Descriptors.NumRotatableBonds(Mols)

    return mw, logp, hbd, hba, tpsa, rings, rot

# Add properties to DataFrame
data[["MolWeight", "LogP", "HBD", "HBA", "TPSA", "Rings", "Rotatable_Bonds"]] = data["Mols"].apply(
    lambda m: pd.Series(calc_properties(m))
)
#lambda m: pd.Series(calc_properties(m))\\a molecule m,send it to calc_properties(), make the returned values into a Series."
#lambda used for one line function

data

data.to_csv("Drug_Properties.csv", index = False)  #index=True → 0,1,2..in CSV index column

                                                  #index=False → index clean CSV(no extra column in csv)

from rdkit.Chem import Draw
from rdkit.Chem.Draw import rdMolDraw2D
from IPython import display
from IPython.display import SVG,display
import math

"""## Molecule Grid's Visual Output"""

molecule_list = data["Mols"].tolist()
molecule_list

from rdkit.Chem.Draw import rdMolDraw2D
def show_grid(Mols, cols = 3, cell = 220):

  Mols = [ m for m in Mols if m is not None ]    #removing none values from mol for error
  rows = math.ceil(len(Mols) / cols)
  drawer = rdMolDraw2D.MolDraw2DSVG(cols*cell, rows*cell, cell, cell)
  drawer.DrawMolecules(Mols)
  drawer.FinishDrawing()
  display(SVG(drawer.GetDrawingText()))

  molecule_list = data["Mols"].tolist()  #panda series -> normal python list (RDkit Drawing fn wants Python list, not Panda)


show_grid(molecule_list, cols=3, cell=220)

"""# Scatter Plot (LogP vs Molecular Weight)"""

print(data.columns)

import matplotlib.pyplot as plt

plt.scatter(data["MolWeight"], data["LogP"])

for i, name in enumerate(data["Molecules Name"]):

    plt.text(data["MolWeight"][i], data["LogP"][i], name)

plt.xlabel("Molecular Weight")
plt.ylabel("LogP")
plt.title("LogP vs Molecular Weight")
plt.grid(True)
plt.show()



"""# **Drug-Likeness Check (Lipinski's Rule of 5)**
* It's matter bcz : small molecule absorbs better, pass through cell membrane more easily, Good oral bioavailability.
*  Its a measure of a molecule as an oral-drug




"""

def lipinski_pass(row):
    return (
        row["MolWeight"] < 500 and
        row["LogP"] < 5 and
        row["HBD"] <= 5 and
        row["HBA"] <= 10
    )                                                     # Function will return True, if all 4 condition meets

data["Lipinski"] = data.apply(lipinski_pass, axis = 1)    # axis 1 = fn will add row-wise in dataframe
data

data = data.drop(columns = "Mols")
data.to_csv("Drug_Properties_Clean_Data.csv", index = False)
data